jhipster-prod-postgresql:
  container_name: jhipster-prod-postgresql
  image: postgres
  # volumes:
  # - ~/volumes/jhipster/jhipster/prod-postgresql/:/var/lib/postgresql/
  environment:
  - POSTGRES_USER=jhipster
  - POSTGRES_PASSWORD=
  ports:
  - "5432:5432"

